name: Install EventMachine gem

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, macos-10.15 ]
        ruby: [ 2.2, 2.3.1, 2.3, 2.4.1, 2.4 ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, openssl
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: openssl
          brew: openssl

      - name: Version Info & Install EventMachine gem
        timeout-minutes: 5
        run: |
          # show version info & install gem
          gcc --version
          echo ''
          ruby -v
          echo ''
          gem install -N eventmachine
